# Default values for nginx-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: psql-spilo-test

replicaCount: 2

deployment:
  namespace: psql-spilo-test

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
