apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "deploy.labels" . | nindent 4 }}
