apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "k8s-nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "k8s-nginx-ingress.labels" . | nindent 4 }}
